const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
  const page = await browser.newPage();
  page.on('pageerror', err => console.log('PAGE EXCEPTION:', err.message));
  let apiCalled = false;
  await page.goto('http://localhost:3000');
  await page.click('.login-switch');
  const ts = Date.now();
  await page.fill('#regName', 'Return Date Test');
  await page.fill('#regUsername', 'returndate_' + ts);
  await page.fill('#regPhone', '+3514' + ts.toString().slice(-8));
  await page.selectOption('#regCountry', 'Portugal');
  await page.fill('#regEmail', 'returndate' + ts + '@test.com');
  await page.fill('#regPassword', 'senha1234forte');
  await page.click('button:has-text("Criar conta")');
  await page.waitForSelector('#mainApp', { state: 'visible', timeout: 8000 });
  await page.evaluate(() => {
    const bounds = { getSouth: () => 36.8, getNorth: () => 42.2, getWest: () => -9.6, getEast: () => -6.1 };
    const chainable = { setView: () => chainable, addTo: () => chainable, invalidateSize: () => {}, on: () => chainable, removeLayer: () => chainable, hasLayer: () => false, clearLayers: () => chainable, addLayer: () => chainable, bindPopup: () => chainable, setLatLng: () => chainable, remove: () => {}, getBounds: () => bounds };
    window.L = { map: () => chainable, tileLayer: () => chainable, layerGroup: () => chainable, marker: () => chainable, divIcon: () => ({}), polyline: () => chainable, icon: () => ({}) };
    window.fetch = ((realFetch) => (url, opts) => {
      if (String(url).startsWith('/api/metro/status')) return Promise.resolve(new Response(JSON.stringify({ lines: [] }), { status: 200 }));
      if (String(url).startsWith('/api/transport/buses')) return Promise.resolve(new Response(JSON.stringify([]), { status: 200 }));
      if (String(url).startsWith('/api/transport/flight-price/offers')) window.__apiCalled = true;
      return realFetch(url, opts);
    })(window.fetch.bind(window));
  });
  await page.evaluate(() => openTransportScreen());
  await page.click('.transport-tab[data-tab="priceSearch"]');
  await page.waitForTimeout(200);
  await page.click('.price-mode-tab[data-mode="flight"]');
  await page.waitForTimeout(300);
  await page.selectOption('#fpOriginInput', 'LIS');
  await page.selectOption('#fpDestinationInput', 'TMS');
  await page.fill('#fpDateInput', '2026-12-25');
  await page.fill('#fpReturnDateInput', '2026-12-18');
  await page.click('button:has-text("Pesquisar voos")');
  await page.waitForTimeout(300);
  const text = await page.evaluate(() => document.getElementById('fpResults').textContent);
  const called = await page.evaluate(() => window.__apiCalled === true);
  console.log('Mostra mensagem amigavel sobre a data de volta:', text.includes('não pode ser antes'));
  console.log('Nao chega a chamar a API (validado no cliente primeiro):', !called);
  await browser.close();
})().catch(e => { console.error('TEST FAILED:', e); process.exit(1); });
